### ISSUE TITLE
Replace Jsoup with Kotlin MPP compatible code

### ISSUE THREAD

**Issue by nomisRev** [timrijckaert/goplay-service#13]
JSoup is a JVM library, and this hinders the base library becoming Kotlin MPP.

We should either opt for manual parsing, or looking for a Kotlin MPP compatible JSoup variant.

Alternatively we can leverage `expect/actual` and push down the platform based code since there is not a lot of JSoup based code which makes the duplication between platforms not horrible.

**Comment by timrijckaert** [comment]
Let’s see if we can even ditch Jsoup alltogether and go for simple Regex to extract the JSON data
